name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore secure-task-api.sln

      - name: Build
        run: dotnet build secure-task-api.sln --no-restore --configuration Release

      - name: Run tests
        run: dotnet test SecureTaskApi.Tests/SecureTaskApi.Tests.csproj --configuration Release --verbosity normal

      - name: Build Docker image
        run: docker build -t secure-task-api:latest .
